# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-09 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Enter a holding symbol (e.g. aapl)', max_length=10)),
                ('name', models.CharField(help_text='Enter the company name', max_length=20)),
                ('price', models.CharField(help_text='Enter the current price', max_length=10)),
                ('shares', models.CharField(help_text='Enter the number of shares owned', max_length=20)),
            ],
        ),
    ]
